# Complete help on configuration: https://dystroy.org/bacon/config/

default_job = "clippy-all"

[jobs.clippy-all]
command = ["cargo", "clippy", "--all-targets", "--", "-W", "clippy::pedantic"]

[jobs.test]
command = ["cargo", "test", "--"]
need_stdout = true

[jobs.doc]
command = ["cargo", "doc", "--no-deps"]

[jobs.doc-open]
command = ["cargo", "doc", "--no-deps", "--open"]
on_success = "back"

[jobs.run]
command = ["cargo", "run", "--"]
need_stdout = true
allow_warnings = true
background = true

[keybindings]
c = "job:clippy-all"
d = "job:doc"
ctrl-d = "job:doc-open"
